[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "python_os"
version = "0.1.0"
description = "A simple Python OS project"
requires-python = ">=3.8"
dependencies = [
    "pyperclip==1.8.2",
]

[project.optional-dependencies]
dev = [
    "pytest==7.3.1",
    "pylint==2.17.4",
    "black==23.3.0",
    "build==0.10.0",
]

[tool.setuptools]
packages = ["python_os"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pylint.messages_control]
disable = [
    "C0111",  # missing-docstring
]